services:
  - type: web
    name: mediafire-api
    env: node
    buildCommand: |
      # Install Chrome
      curl -LO "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" \
      && apt-get update \
      && apt-get install -y ./google-chrome-stable_current_amd64.deb \
      && rm google-chrome-stable_current_amd64.deb \
      && npm ci
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable - type: web
    name: mediafire-api
    env: node
  # Create cache dir and install Chromium for Puppeteer into Render's cache path during build
  buildCommand: "mkdir -p /opt/render/.cache/puppeteer && export PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer && npm ci && npx puppeteer@24.19.0 install --product=chrome"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
    plan: free
