services:
  - type: web
    name: mediafire-api
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
